spring:
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect #org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

logging:
  level:
    root: info
    MiniProject:
      BasicBoard: debug
